[package]
name = "ysip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.15.1"
cw20-base = {version = "0.15.1", features = ["library"]}
cosmwasm-std = "1.1.2"
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = "1.0.37"

[dev-dependencies]
cosmwasm-schema = "1.1.2"